version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    command: mongod --replSet rs0
    healthcheck:
      test: |
        mongosh --eval "try { rs.status().ok } catch (e) { rs.initiate({ _id: 'rs0', members: [{ _id: 0, host: 'localhost:27017' }] }).ok }"
      start_period: 0s
      interval: 500ms
      timeout: 5s
      retries: 5
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - backend-mongodb:/data/db
    networks:
      - backend
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
    volumes:
      - 'backend-redis:/data'
    networks:
      - backend
networks:
  backend:
    driver: bridge
volumes:
  backend-mongodb:
    driver: local
  backend-redis:
    driver: local